### PR TITLE
Check to see username is null before displaying

### LINKED ISSUE #498: java.lang.NullPointerException
**Number:** 	 414

**Status:** 	 New

**Reported At:** 	 2018-04-03 13:09:48 UTC

**Email:** 	 

**URL:** 	 https://insta.co/crashes/3B1p0G6KPnos3P32pnBtSg

**App Version:** 	 2.0 (15)

**Current View:** 	 org.fundacionparaguaya.advisorapp.ui.dashboard.DashActivity

**Device:** 	 samsung SM-T230

**Location:** 	 Asunción, Paraguay

**Duration:** 	 2

**Connectivity:** 	 Carrier: , WiFi: FP8 - Sala Naranja

**Memory:** 	 902.0/1319.0 MB

**Storage:** 	 2.184/4.941 GB

**Orientation:** 	 portrait

**Screen Size:** 	 800x1280

**Density:** 	 mdpi

**Battery:** 	 64, Unplugged

**User Data:** 	 

**User Steps:**
```
1522760985871 org.fundacionparaguaya.advisorapp.ui.dashboard.DashActivity was created.

1522760986106 org.fundacionparaguaya.advisorapp.ui.dashboard.DashActivity was started.

1522760986208 org.fundacionparaguaya.advisorapp.ui.dashboard.DashActivity was resumed.

1522760988372 In activity org.fundacionparaguaya.advisorapp.ui.dashboard.DashActivity: View(imageView_icon) of type android.support.v7.widget.AppCompatImageView received a click event


```

**Console Log:**
```
 0x6f at 0x0004

1522760988415  I/dalvikvm(12936): Could not find method android.widget.Button.getAutoSizeStepGranularity, referenced from method android.support.v7.widget.AppCompatButton.getAutoSizeStepGranularity

1522760988415  W/dalvikvm(12936): VFY: unable to resolve virtual method 39467: Landroid/widget/Button;.getAutoSizeStepGranularity ()I

1522760988415  D/dalvikvm(12936): VFY: replacing opcode 0x6f at 0x0004

1522760988415  I/dalvikvm(12936): Could not find method android.widget.Button.getAutoSizeTextAvailableSizes, referenced from method android.support.v7.widget.AppCompatButton.getAutoSizeTextAvailableSizes

1522760988415  W/dalvikvm(12936): VFY: unable to resolve virtual method 39468: Landroid/widget/Button;.getAutoSizeTextAvailableSizes ()[I

1522760988415  D/dalvikvm(12936): VFY: replacing opcode 0x6f at 0x0004

1522760988415  I/dalvikvm(12936): Could not find method android.widget.Button.getAutoSizeTextType, referenced from method android.support.v7.widget.AppCompatButton.getAutoSizeTextType

1522760988415  W/dalvikvm(12936): VFY: unable to resolve virtual method 39469: Landroid/widget/Button;.getAutoSizeTextType ()I

1522760988415  D/dalvikvm(12936): VFY: replacing opcode 0x6f at 0x0006

1522760988415  I/dalvikvm(12936): Could not find method android.widget.Button.setAutoSizeTextTypeUniformWithConfiguration, referenced from method android.support.v7.widget.AppCompatButton.setAutoSizeTextTypeUniformWithConfiguration

1522760988415  W/dalvikvm(12936): VFY: unable to resolve virtual method 39478: Landroid/widget/Button;.setAutoSizeTextTypeUniformWithConfiguration (IIII)V

1522760988415  D/dalvikvm(12936): VFY: replacing opcode 0x6f at 0x0004

1522760988415  I/dalvikvm(12936): Could not find method android.widget.Button.setAutoSizeTextTypeUniformWithPresetSizes, referenced from method android.support.v7.widget.AppCompatButton.setAutoSizeTextTypeUniformWithPresetSizes

1522760988415  W/dalvikvm(12936): VFY: unable to resolve virtual method 39479: Landroid/widget/Button;.setAutoSizeTextTypeUniformWithPresetSizes ([II)V

1522760988415  D/dalvikvm(12936): VFY: replacing opcode 0x6f at 0x0004

1522760988415  I/dalvikvm(12936): Could not find method android.widget.Button.setAutoSizeTextTypeWithDefaults, referenced from method android.support.v7.widget.AppCompatButton.setAutoSizeTextTypeWithDefaults

1522760988415  W/dalvikvm(12936): VFY: unable to resolve virtual method 39480: Landroid/widget/Button;.setAutoSizeTextTypeWithDefaults (I)V

1522760988415  D/dalvikvm(12936): VFY: replacing opcode 0x6f at 0x0004

1522760988415  D/AndroidRuntime(12936): Shutting down VM

1522760988415  W/dalvikvm(12936): threadid=1: thread exiting with uncaught exception (group=0x41ab3c08)

1522760988455  W/ContextImpl(12936): Failed to ensure directory: /storage/extSdCard/Android/data/org.fundacionparaguaya.advisorapp/cache

1522760988455  W/ContextImpl(12936): Failed to ensure directory: /storage/extSdCard/Android/data/org.fundacionparaguaya.advisorapp/cache


```

**Instabug Log:**
```

```

### PR DESCRIPTION
**Pull request by alextac98**
# Description 

Adds a check to see if username is null

# Changes 

- Add check for null username
- If username is null, display "No Username" 

# Issues 

- Fixes #498

# Screenshots 

# Tests 

This code has been tested in the following ways:
- Tasks:
  - [x] Logged in to the application
  - [ ] Fill out a snapshot for a new family
  - [ ] Fill out a snapshot for an existing family
  - [ ] Fill out priorities for a snapshot
  - [x] View a family and it's priorities
- API Level:
  - [ ] API Level 19
  - [ ] API Level 22
  - [x] API Level 25
- Screen Size:
  - [ ] 7" screen size
  - [x] 8" screen size
  - [ ] 10" screen size

### CODE REVIEW

File: app/src/main/java/org/fundacionparaguaya/advisorapp/ui/settings/SettingsStackedFrag.java [hunk 1]
```diff
@@ -60,7 +60,12 @@ public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup c
         mReleaseNum = view.findViewById(R.id.settings_releasenumber);
         String version = "";
 
-        mUsername.setText(mSettingsViewModel.getAuthManager().getUser().getUsername());
+        if (mSettingsViewModel.getAuthManager().getUser().getUsername() != null){
```
Comment (bhylak) [inline app/src/main/java/org/fundacionparaguaya/advisorapp/ui/settings/SettingsStackedFrag.java]: change to

`String userName = mSettingsViewModel.getAuthManger().getUser().getUsername();`

then proceed with checks.

i'm not sure that the user name itself is null vs the user. also the settings view model should provide the user name.
