### PR TITLE
Fixed a lot of bugs.. #96, #95, #93, #91, #90, #89, #88, #87, #86, #85 and #84.

### LINKED ISSUE #84: Translation for familias heading

### LINKED ISSUE #85: Add under construction pages for map, archive and settings

### LINKED ISSUE #86: Priorities should have under construction message

### LINKED ISSUE #87: Two headings for the all families

### LINKED ISSUE #88: Blank space above all families (was planned for schedule)

### LINKED ISSUE #89: Android status bar should match application color

### LINKED ISSUE #90: Remove toast when switching tabs

### LINKED ISSUE #91: Fragment transitions (left->right or right<-left)

### LINKED ISSUE #93: Snapshot selection dropdown should overlap selector
┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;download_asset?asset_id&#x3D;546477035993530">image.png</a>

### LINKED ISSUE #95: View model loses family when switching between tabs
With family open, switch to map and then go back to family page

### LINKED ISSUE #96: Indicators tab loses state when switching between tabs (current snapshot goes back to default)

### PR DESCRIPTION
**Pull request by bhylak**
Fixes #96, fixed #95 , fixes #93, fixes #91, fixes #90, fixes #89, fixes #88, fixes #87, fixes #86, fixes #85 and fixes #84

~The app bar color will only change after lolipop (no easy way around this)~ App bar color should change when possible, using support library/primary dark. 

Implemented under construction pages for all of the pages, added to priorities.

Also cleaned up TabbedFrag implementation to reduce redundancy. (It's really cool now) 

Removed *some* hard coded strings from the family's page, namely the title, but there are more that will need to be worked on. 

The family detail page is pretty messed up right now, but I think it is actually *structured* better now. All of the values were super hard coded before, making it extremely inflexible. It's going to need some work (and it is something we should have caught earlier). Added a bug to our Asana project. 

Found that Google's documentation of LiveData had a big flaw.. It showed observers being added in a fragments onCreate, but because fragments are retained between attaching/detatching, only onCreateView and onDestroyView are called and the view will never be updated.

### CODE REVIEW

File: app/src/main/java/org/fundacionparaguaya/advisorapp/fragments/AbstractTabbedFrag.java [hunk 1]
```diff
@@ -86,17 +87,21 @@ public void setInitialFragment(StackedFrag frag) {
...
      * @param frag
      */
-    private FragmentTransaction makeFragmentTransaction(StackedFrag frag) {
+    private FragmentTransaction makeFragmentTransaction(AbstractStackedFrag frag) {
 
         FragmentTransaction ft = getChildFragmentManager().beginTransaction();
+
+        ft.setCustomAnimations(R.anim.enter_from_right, R.anim.exit_to_left,
+                R.anim.enter_from_left, R.anim.exit_to_right);
+        //ft.setCustomAnimations(android.R.anim.slide_in_left, android.R.anim.slide_out_right);
```
Comment (krconv) [inline app/src/main/java/org/fundacionparaguaya/advisorapp/fragments/AbstractTabbedFrag.java]: Debug line

File: app/src/main/java/org/fundacionparaguaya/advisorapp/activities/LoginActivity.java [hunk 2]
```diff
@@ -19,6 +21,12 @@ protected void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
         setContentView(R.layout.activity_login);
 
+       /* //only supported after Lollipop
```
Comment (krconv) [inline app/src/main/java/org/fundacionparaguaya/advisorapp/activities/LoginActivity.java]: Commented out code

**Comment by krconv** [comment]
image
Looks like the view of the families isn't forced to fill the full screen; after switching tabs this resolves itself, so it's probably just a fill_parent missing somewhere
