### PR TITLE
Fix LifeMap bugs

### LINKED ISSUE #338: After new survey is completed, the lifemap and priorities page do not update to the latest survey

### LINKED ISSUE #450: Drop down for snapshot isnt click able after rotate
**Title:** Drop down for snapshot isnt click able after rotate

**Number:** 29

**Status:** New

**Reported At:** 2018-03-27 11:21:47 UTC

**Email:** kodey@krconv.com

**URL:** https://insta.co/bugs/fcCGCT4s

**Categories:** Report a Problem

**App Version:** 1.4.0-SNAPSHOT-dirty (13)

**Current View:** org.fundacionparaguaya.advisorapp.activities.DashActivity

**Device:** samsung SM-T285, OS Level 22

**Location:** , 

**Duration:** 20

**Connectivity:** Carrier: , WiFi: DIRECT-2B-HP SF-765

**Memory:** 1001.0/1416.0 MB

**Storage:** 1.15/4.897 GB

**Orientation:** portrait

**Screen Size:** 800x1280

**Density:** mdpi

**Battery:** 41, Unplugged

**User Data:**

**User Steps:**

```
activity org.fundacionparaguaya.advisorapp.activities.DashActivity: View(tv_topbar_tabtitle) of type android.support.v7.widget.AppCompatTextView received a click event

1522149684219 In activity org.fundacionparaguaya.advisorapp.activities.DashActivity: View(allfamilies_card_image) of type com.facebook.drawee.view.SimpleDraweeView received a click event

1522149685183 In activity org.fundacionparaguaya.advisorapp.activities.DashActivity: View(spinner_familylifemap_snapshot) of type org.fundacionparaguaya.advisorapp.viewcomponents.EvenBetterSpinner received a click event

1522149686175 In activity org.fundacionparaguaya.advisorapp.activities.DashActivity: View(spinner_familylifemap_snapshot) of type org.fundacionparaguaya.advisorapp.viewcomponents.EvenBetterSpinner received a click event

1522149687024 org.fundacionparaguaya.advisorapp.activities.DashActivity was paused.

1522149687056 org.fundacionparaguaya.advisorapp.activities.DashActivity was stopped.

1522149687106 org.fundacionparaguaya.advisorapp.activities.DashActivity was destroyed.

1522149687177 org.fundacionparaguaya.advisorapp.activities.DashActivity was created.

1522149687315 org.fundacionparaguaya.advisorapp.activities.DashActivity was started.

1522149687418 org.fundacionparaguaya.advisorapp.activities.DashActivity was resumed.

1522149688678 In activity org.fundacionparaguaya.advisorapp.activities.DashActivity: View(spinner_familylifemap_snapshot) of type org.fundacionparaguaya.advisorapp.viewcomponents.EvenBetterSpinner received a click event

1522149689545 In activity org.fundacionparaguaya.advisorapp.activities.DashActivity: View(rv_lifemap_indicators) of type android.support.v7.widget.RecyclerView received a click event

1522149690423 In activity org.fundacionparaguaya.advisorapp.activities.DashActivity: View(iv_indicatoritem_color) of type android.support.v7.widget.AppCompatImageView received a click event

1522149691025 In activity org.fundacionparaguaya.advisorapp.activities.DashActivity: View of type android.support.design.widget.TabLayout$TabView received a click event

1522149691759 In activity org.fundacionparaguaya.advisorapp.activities.DashActivity: View of type android.support.design.widget.TabLayout$TabView received a click event

1522149692466 In activity org.fundacionparaguaya.advisorapp.activities.DashActivity: View(spinner_familylifemap_snapshot) of type org.fundacionparaguaya.advisorapp.viewcomponents.EvenBetterSpinner received a click event

1522149693485 In activity org.fundacionparaguaya.advisorapp.activities.DashActivity: View(spinner_familylifemap_snapshot) of type org.fundacionparaguaya.advisorapp.viewcomponents.EvenBetterSpinner received a click event

1522149694009 In activity org.fundacionparaguaya.advisorapp.activities.DashActivity: View(spinner_familylifemap_snapshot) of type org.fundacionparaguaya.advisorapp.viewcomponents.EvenBetterSpinner received a click event

1522149703342 org.fundacionparaguaya.advisorapp.activities.DashActivity was paused.


```

**Console Log:**

```
ry: /storage/extSdCard/Android/data/org.fundacionparaguaya.advisorapp/files

1522149711378  D/AbsListView(19119): Get MotionRecognitionManager

1522149711378  E/MotionRecognitionManager(19119): mSContextService = null

1522149711378  E/MotionRecognitionManager(19119): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@29ae6237

1522149712469  D/ViewRootImpl(19119): ViewPostImeInputStage ACTION_DOWN

1522149724481  D/ViewRootImpl(19119): ViewPostImeInputStage ACTION_DOWN

1522149742789  D/ViewRootImpl(19119): ViewPostImeInputStage ACTION_DOWN

1522149742899  W/ContextImpl(19119): Failed to ensure directory: /storage/extSdCard/Android/data/org.fundacionparaguaya.advisorapp/files

1522149742899  I/Timeline(19119): Timeline: Activity_launch_request id:org.fundacionparaguaya.advisorapp time:281448156

1522149742909  W/ContextImpl(19119): Failed to ensure directory: /storage/extSdCard/Android/data/org.fundacionparaguaya.advisorapp/files

1522149742909  W/System.err(19119): java.io.FileNotFoundException: /storage/emulated/0/Android/data/org.fundacionparaguaya.advisorapp/files/instabug/attachments/bug_1522149703204_.jpg: open failed: ENOENT (No such file or directory)

1522149742909  W/System.err(19119): 	at libcore.io.IoBridge.open(IoBridge.java:456)

1522149742909  W/System.err(19119): 	at java.io.FileInputStream.init(FileInputStream.java:76)

1522149742909  W/System.err(19119): 	at com.instabug.library.util.BitmapUtils.compressBitmapAndSave(BitmapUtils.java:94)

1522149742909  W/System.err(19119): 	at com.instabug.bug.d.d(LiveBugManager.java:198)

1522149742909  W/System.err(19119): 	at com.instabug.bug.d.b(LiveBugManager.java:39)

1522149742909  W/System.err(19119): 	at com.instabug.bug.d$1.run(LiveBugManager.java:133)

1522149742909  W/System.err(19119): 	at java.lang.Thread.run(Thread.java:818)

1522149742909  W/System.err(19119): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)

1522149742909  W/System.err(19119): 	at libcore.io.Posix.open(Native Method)

1522149742909  W/System.err(19119): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)

1522149742909  W/System.err(19119): 	at libcore.io.IoBridge.open(IoBridge.java:442)

1522149742909  W/System.err(19119): 	... 6 more

1522149742939  D/SensorManager(19119): unregisterListener ::

1522149742969  V/ActivityThread(19119): updateVisibility : ActivityRecord38905954 token=android.os.BinderProxy@cf5a3a9 org.fundacionparaguaya.advisorapp/org.fundacionparaguaya.advisorapp.activities.DashActivity show : true

1522149742999  D/PhoneWindow(19119): *FMB* installDecor mIsFloating : false

1522149742999  D/PhoneWindow(19119): *FMB* installDecor flags : -2139029248

1522149743019  D/SensorManager(19119): registerListener :: 0, K2HH Acceleration , 200000, 0,

1522149743069  D/PhoneWindow(19119): *FMB* isFloatingMenuEnabled mFloatingMenuBtn : null

1522149743069  D/PhoneWindow(19119): *FMB* isFloatingMenuEnabled return false


```

**Instabug Log:**

```

```

[?1522149731 image attachment ](https://s3.amazonaws.com/instabug-pro/attachments/states/157500551/1a8c08c3dbbfa5bfdca64d0459aaa8aa_original/65688690/bug_1522149703204_.jpg)

### PR DESCRIPTION
**Pull request by alextac98**
# Description 

Fix bugs in the LifeMap on the FamilyDetailsFragment

# Changes 

- Fix Lifemap getting reset on rotation
- Fix Dropdown not clickable after rotation
- Fix lifemap and priorities page not updating to the last survey
# Issues 
- The Life map gets reset to original after rotation (#451)

# Fixes
- Fixes #450 
- Fixes #338 

# Tests 

This code has been tested in the following ways:
- Tasks:
  - [x] Logged in to the application
  - [x] Fill out a snapshot for a new family
  - [x] Fill out a snapshot for an existing family
  - [x] Fill out priorities for a snapshot
  - [x] View a family and it's priorities
- API Level:
  - [x] API Level 19
  - [ ] API Level 22
  - [x] API Level 25
- Screen Size:
  - [x] 7" screen size
  - [ ] 8" screen size
  - [x] 10" screen size

### CODE REVIEW

File: app/src/main/java/org/fundacionparaguaya/advisorapp/ui/families/detail/FamilyLifeMapFragment.java [hunk 1]
```diff
@@ -51,7 +51,8 @@ public void onCreate(@Nullable Bundle savedInstanceState) {
         mFamilyDetailViewModel = ViewModelProviders
                 .of(getParentFragment(), mViewModelFactory)
                 .get(FamilyDetailViewModel.class);
-
+        //Saves the instance on rotation
+        setRetainInstance(true);
```
Comment (bhylak) [inline app/src/main/java/org/fundacionparaguaya/advisorapp/ui/families/detail/FamilyLifeMapFragment.java]: this change would cause mountains of memory leaks: https://stackoverflow.com/questions/13421945/retained-fragments-with-ui-and-memory-leaks?answertab=votes#tab-top

Comment (bhylak) [reply app/src/main/java/org/fundacionparaguaya/advisorapp/ui/families/detail/FamilyLifeMapFragment.java]: it's just a bandaid fix to the problem. you're preventing the fragment from ever actually experiencing the configuration change.

Comment (alextac98) [reply app/src/main/java/org/fundacionparaguaya/advisorapp/ui/families/detail/FamilyLifeMapFragment.java]: Fixed in fd4dcc5
