### PR TITLE
Fix order issue with survey questions

### LINKED ISSUE #537: Questions are not in the right order. It is not in the same order as the web version. It skips for example LAST NAME after FIRST Name
**Title:** Questions are not in the right order. It is not in the same order as the web version. It skips for example LAST NAME after FIRST Name

**Number:** 41

**Status:** New

**Reported At:** 2018-04-12 21:31:29 UTC

**Email:** egustale@fundacionparaguaya.org.py

**URL:** https://insta.co/bugs/nTaolacDiOb2cdlfwPWLow

**Categories:** Report a Problem

**App Version:** 2.0.5 (20)

**Current View:** org.fundacionparaguaya.adviserplatform.ui.survey.SurveyActivity

**Device:** samsung SM-T560, OS Level 19

**Location:** Asunción, Paraguay

**Duration:** 98

**Screen Size:** 800x1280

**Density:** mdpi

**User Data:**

**User Steps:**

```
atform.ui.dashboard.DashActivity was paused.

1523568665151 org.fundacionparaguaya.adviserplatform.ui.survey.SurveyActivity was created.

1523568665157 org.fundacionparaguaya.adviserplatform.ui.survey.SurveyActivity was started.

1523568665184 org.fundacionparaguaya.adviserplatform.ui.survey.SurveyActivity was resumed.

1523568665570 org.fundacionparaguaya.adviserplatform.ui.dashboard.DashActivity was stopped.

1523568673421 In activity org.fundacionparaguaya.adviserplatform.ui.survey.SurveyActivity: View of type android.widget.RelativeLayout received a click event

1523568674661 In activity org.fundacionparaguaya.adviserplatform.ui.survey.SurveyActivity: View of type android.widget.RelativeLayout received a click event

1523568676559 In activity org.fundacionparaguaya.adviserplatform.ui.survey.SurveyActivity: View of type android.widget.RelativeLayout received a click event

1523568677425 In activity org.fundacionparaguaya.adviserplatform.ui.survey.SurveyActivity: View of type android.support.v7.widget.AppCompatTextView received a click event

1523568680541 In activity org.fundacionparaguaya.adviserplatform.ui.survey.SurveyActivity: View of type android.widget.RelativeLayout received a click event

1523568681569 In activity org.fundacionparaguaya.adviserplatform.ui.survey.SurveyActivity: View(et_questiontext_answer) of type android.support.v7.widget.AppCompatEditText received a click event

1523568683272 In activity org.fundacionparaguaya.adviserplatform.ui.survey.SurveyActivity: View of type android.widget.RelativeLayout received a click event

1523568684857 In activity org.fundacionparaguaya.adviserplatform.ui.survey.SurveyActivity: View of type android.widget.RelativeLayout received a click event

1523568686594 In activity org.fundacionparaguaya.adviserplatform.ui.survey.SurveyActivity: View(et_questiontext_answer) of type android.support.v7.widget.AppCompatEditText received a click event

1523568694252 In activity org.fundacionparaguaya.adviserplatform.ui.survey.SurveyActivity: View of type android.widget.RelativeLayout received a click event

1523568695633 In activity org.fundacionparaguaya.adviserplatform.ui.survey.SurveyActivity: View of type android.widget.LinearLayout received a click event

1523568696617 In activity org.fundacionparaguaya.adviserplatform.ui.survey.SurveyActivity: View of type android.widget.LinearLayout received a click event

1523568698715 In activity org.fundacionparaguaya.adviserplatform.ui.survey.SurveyActivity: View of type android.widget.RelativeLayout received a click event

1523568700108 In activity org.fundacionparaguaya.adviserplatform.ui.survey.SurveyActivity: View(et_questiontext_answer) of type android.support.v7.widget.AppCompatEditText received a click event

1523568703437 In activity org.fundacionparaguaya.adviserplatform.ui.survey.SurveyActivity: View of type android.widget.RelativeLayout received a click event

1523568712126 org.fundacionparaguaya.adviserplatform.ui.survey.SurveyActivity was paused.


```

**Console Log:**

```
r 3029968-byte allocation

1523568803822  D/dalvikvm( 5505): GC_FOR_ALLOC freed 2996K, 35 free 28990K/44496K, paused 80ms, total 81ms

1523568804043  D/dalvikvm( 5505): GC_FOR_ALLOC freed 38K, 29 free 31949K/44496K, paused 95ms, total 95ms

1523568804043  I/dalvikvm-heap( 5505): Grow heap (frag case) to 38.007MB for 3029968-byte allocation

1523568804383  D/dalvikvm( 5505): GC_FOR_ALLOC freed 8951K, 43 free 28990K/50416K, paused 87ms, total 87ms

1523568804723  D/dalvikvm( 5505): GC_FOR_ALLOC freed 5989K, 35 free 28989K/44492K, paused 87ms, total 87ms

1523568804933  D/dalvikvm( 5505): GC_FOR_ALLOC freed 2996K, 31 free 28989K/41536K, paused 84ms, total 84ms

1523568804933  I/dalvikvm-heap( 5505): Grow heap (frag case) to 34.117MB for 3029968-byte allocation

1523568805134  D/dalvikvm( 5505): GC_FOR_ALLOC freed 2993K, 35 free 28989K/44496K, paused 81ms, total 81ms

1523568805334  D/dalvikvm( 5505): GC_FOR_ALLOC freed 2994K, 31 free 28988K/41536K, paused 82ms, total 82ms

1523568805534  D/dalvikvm( 5505): GC_FOR_ALLOC freed 2993K, 35 free 28988K/44496K, paused 81ms, total 81ms

1523568806305  D/dalvikvm( 5505): GC_FOR_ALLOC freed 3004K, 35 free 28987K/44496K, paused 84ms, total 84ms

1523568816505  W/ContextImpl( 5505): Failed to ensure directory: /storage/extSdCard/Android/data/org.fundacionparaguaya.adviserplatform/files

1523568816515  I/Timeline( 5505): Timeline: Activity_launch_request id:org.fundacionparaguaya.adviserplatform time:10062670

1523568816525  W/ContextImpl( 5505): Failed to ensure directory: /storage/extSdCard/Android/data/org.fundacionparaguaya.adviserplatform/files

1523568816525  W/System.err( 5505): java.io.FileNotFoundException: /storage/emulated/0/Android/data/org.fundacionparaguaya.adviserplatform/files/instabug/attachments/bug_1523568711985_.jpg: open failed: ENOENT (No such file or directory)

1523568816525  W/System.err( 5505): 	at libcore.io.IoBridge.open(IoBridge.java:409)

1523568816525  W/System.err( 5505): 	at java.io.FileInputStream.init(FileInputStream.java:78)

1523568816525  W/System.err( 5505): 	at com.instabug.library.util.BitmapUtils.compressBitmapAndSave(BitmapUtils.java:94)

1523568816525  W/System.err( 5505): 	at com.instabug.bug.d.d(LiveBugManager.java:198)

1523568816525  W/System.err( 5505): 	at com.instabug.bug.d.b(LiveBugManager.java:39)

1523568816525  W/System.err( 5505): 	at com.instabug.bug.d$1.run(LiveBugManager.java:133)

1523568816525  W/System.err( 5505): 	at java.lang.Thread.run(Thread.java:841)

1523568816525  W/System.err( 5505): Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)

1523568816525  W/System.err( 5505): 	at libcore.io.Posix.open(Native Method)

1523568816525  W/System.err( 5505): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)

1523568816525  W/System.err( 5505): 	at libcore.io.IoBridge.open(IoBridge.java:393)

1523568816525  W/System.err( 5505): 	... 6 more

1523568816555  D/SensorManager( 5505): unregisterListener ::


```

**Instabug Log:**

```

```

[?1523568692 image attachment ](https://s3.amazonaws.com/instabug-pro/attachments/states/165302954/9250a00a1fa5db66d09e77f7c64b5280_original/70193270/bug_1523568711985_.jpg)

### PR DESCRIPTION
**Pull request by krconv**
# Changes 

- Changes the `IrMapper` to use the `ui:order` instead of the `ui:...Questions` lists
  - This was made because the assumption that the individual `ui:...Questions` lists were in order is not true
  - Updated test cases to test for this problem
- Adds `toString` methods to most of the model classes for easier test failure debugging

# Issues 

- Fixes
  - Fixes #537 by using the correct order from the server

# Tests 

This code has been tested in the following ways:
- Tasks:
  - [X] Logged in to the application
  - [ ] Fill out a snapshot for a new family
  - [ ] Fill out a snapshot for an existing family
  - [ ] Fill out priorities for a snapshot
  - [X] View a family and it's priorities
- API Level:
  - [ ] API Level 19
  - [X] API Level 22
  - [ ] API Level 25
- Screen Size:
  - [ ] 7" screen size
  - [X] 8" screen size
  - [ ] 10" screen size

### CODE REVIEW

File: app/src/main/java/org/fundacionparaguaya/adviserplatform/data/model/LifeMapPriority.java [hunk 1]
```diff
@@ -72,6 +73,11 @@ public static Builder builder() {
         return new Builder();
     }
 
+    @Override
```
Comment (bhylak) [inline app/src/main/java/org/fundacionparaguaya/adviserplatform/data/model/LifeMapPriority.java]: Was this purposefully added? @krconv

Comment (krconv) [reply app/src/main/java/org/fundacionparaguaya/adviserplatform/data/model/LifeMapPriority.java]: Yes, I added `toString` methods to all of the model classes
